### ISSUE TITLE
next-wp: Build process fails on CloudLinux deployment

### ISSUE THREAD

**Issue by quinnouyang** [quinnouyang/contextual-engineering-site#61]
```
[cergtest3@web next-wp]$ npm run build

> build
> next build

info  - Loaded env from /home/cergtest3/next-wp/.env.local

> Build error occurred
Error: spawn ENOMEM
    at ChildProcess.spawn (node:internal/child_process:420:11)
    at spawn (node:child_process:733:9)
    at fork (node:child_process:169:10)
    at ChildProcessWorker.initialize (/home/cergtest3/next-wp/node_modules/next/dist/compiled/jest-worker/index.js:1:10927)
    at new ChildProcessWorker (/home/cergtest3/next-wp/node_modules/next/dist/compiled/jest-worker/index.js:1:10815)
    at WorkerPool.createWorker (/home/cergtest3/next-wp/node_modules/next/dist/compiled/jest-worker/index.js:1:6315)
    at new BaseWorkerPool (/home/cergtest3/next-wp/node_modules/next/dist/compiled/jest-worker/index.js:1:8183)
    at new WorkerPool (/home/cergtest3/next-wp/node_modules/next/dist/compiled/jest-worker/index.js:1:6111)
    at new Worker (/home/cergtest3/next-wp/node_modules/next/dist/compiled/jest-worker/index.js:1:23381)
    at Object.verifyAndLint (/home/cergtest3/next-wp/node_modules/next/dist/lib/verifyAndLint.js:21:29) {
  errno: -12,
  code: 'ENOMEM',
  syscall: 'spawn'
}
info  - Linting and checking validity of types
```
See:
- https://stackoverflow.com/a/70028995/17778474
- (current workaround) https://stackoverflow.com/questions/73938031/error-jest-worker-just-run-in-cpanel-adonisjs-nextjs-reactjs

**Comment by quinnouyang** [comment]
Current workaround, pending review [e555c55](https://github.com/quinnouyang/contextual-engineering-site/pull/62/commits/e555c55dc38738f203630c5111167a2ccb98601b)

**Comment by quinnouyang** [comment]
Closing for now, to be revisited for better solutions
